development:
  host: localhost
  database: collector_development

test:
  host: localhost
  database: collector_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOLAB_URI'] %>
